
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label Numero1;
	private global::Gtk.Label Resultado1;
	private global::Gtk.Label Numero2;
	private global::Gtk.Entry texto1;
	private global::Gtk.Entry texto2;
	private global::Gtk.Entry resultado;
	private global::Gtk.Button multiplicar;
	private global::Gtk.Button dividir;
	private global::Gtk.Button restar;
	private global::Gtk.Button sumar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero1 = new global::Gtk.Label ();
		this.Numero1.Name = "Numero1";
		this.Numero1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero1");
		this.fixed1.Add (this.Numero1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero1]));
		w1.X = 64;
		w1.Y = 48;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Resultado1 = new global::Gtk.Label ();
		this.Resultado1.Name = "Resultado1";
		this.Resultado1.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.Resultado1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Resultado1]));
		w2.X = 63;
		w2.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero2 = new global::Gtk.Label ();
		this.Numero2.Name = "Numero2";
		this.Numero2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero2");
		this.fixed1.Add (this.Numero2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero2]));
		w3.X = 65;
		w3.Y = 116;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.texto1 = new global::Gtk.Entry ();
		this.texto1.CanFocus = true;
		this.texto1.Name = "texto1";
		this.texto1.IsEditable = true;
		this.texto1.InvisibleChar = '●';
		this.fixed1.Add (this.texto1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.texto1]));
		w4.X = 146;
		w4.Y = 47;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.texto2 = new global::Gtk.Entry ();
		this.texto2.CanFocus = true;
		this.texto2.Name = "texto2";
		this.texto2.IsEditable = true;
		this.texto2.InvisibleChar = '●';
		this.fixed1.Add (this.texto2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.texto2]));
		w5.X = 148;
		w5.Y = 112;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.resultado = new global::Gtk.Entry ();
		this.resultado.CanFocus = true;
		this.resultado.Name = "resultado";
		this.resultado.IsEditable = true;
		this.resultado.InvisibleChar = '●';
		this.fixed1.Add (this.resultado);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.resultado]));
		w6.X = 148;
		w6.Y = 183;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.multiplicar = new global::Gtk.Button ();
		this.multiplicar.CanFocus = true;
		this.multiplicar.Name = "multiplicar";
		this.multiplicar.UseUnderline = true;
		this.multiplicar.Label = global::Mono.Unix.Catalog.GetString ("multiplicar");
		this.fixed1.Add (this.multiplicar);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.multiplicar]));
		w7.X = 264;
		w7.Y = 299;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dividir = new global::Gtk.Button ();
		this.dividir.CanFocus = true;
		this.dividir.Name = "dividir";
		this.dividir.UseUnderline = true;
		this.dividir.Label = global::Mono.Unix.Catalog.GetString ("dividir");
		this.fixed1.Add (this.dividir);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.dividir]));
		w8.X = 360;
		w8.Y = 298;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.restar = new global::Gtk.Button ();
		this.restar.CanFocus = true;
		this.restar.Name = "restar";
		this.restar.UseUnderline = true;
		this.restar.Label = global::Mono.Unix.Catalog.GetString ("restar");
		this.fixed1.Add (this.restar);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.restar]));
		w9.X = 188;
		w9.Y = 299;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.sumar = new global::Gtk.Button ();
		this.sumar.CanFocus = true;
		this.sumar.Name = "sumar";
		this.sumar.UseUnderline = true;
		this.sumar.Label = global::Mono.Unix.Catalog.GetString ("sumar");
		this.fixed1.Add (this.sumar);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.sumar]));
		w10.X = 105;
		w10.Y = 299;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 606;
		this.DefaultHeight = 396;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.multiplicar.Clicked += new global::System.EventHandler (this.OnMultiplicarClicked);
		this.dividir.Clicked += new global::System.EventHandler (this.OnDividirClicked);
		this.restar.Clicked += new global::System.EventHandler (this.OnRestarClicked);
		this.sumar.Clicked += new global::System.EventHandler (this.OnSumarClicked);
	}
}
